name: 'dbt_market'
version: '1.0.0'

profile: 'dbt_market'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_market:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
      
seeds:
  dbt_market:
    +schema: marts